version: "2"
linters:
  default: all
  disable:
    - nlreturn
    - exhaustruct
  settings:
    errcheck:
      disable-default-exclusions: true
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintln
        - fmt.Fprintf
        - (*os.File).Close
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - golift.io
issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
