version: '2'
linters:
  default: all
  disable:
    - nlreturn
    - exhaustruct
    - wsl
  settings:
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
    errcheck:
      disable-default-exclusions: true
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintln
        - fmt.Fprintf
        - (*os.File).Close
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - golift.io
issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
